### ISSUE TITLE
Config Db file

### ISSUE THREAD

**Issue by DrMoskovich** [coelo-donta/SBB-fallblatt#1]
Hello.
Ich bin recht neu in der Programmierung und ich habe eine Frage.
Was muss ich in das Modules.db file schreiben, wenn die Adresse meines Moduls 1 und  der Serieller-Port COM3 ist?
Ich wäre sehr dankbar wenn sie mir diese Frage beantworten könnten.
LG DrMoskovich.

**Comment by coelo-donta** [comment]
Hi, 
falls du nur ein Modul hast, kannst du als erstes alle Einträge aus dem table `modules` löschen (`DELETE FROM modules;`). 
Dann fügst du eine neue Zeile für jedes Modul ein; z.B `INSERT INTO modules (address, type, bladeCount, moduleWidth, moduleColor, textLanguage, is_used, serial_address) VALUES (1, 'minute', 62, 1, 'blue', 'de', 1, '/dev/ttyS2');`
COM3 sollte automatisch auf `/dev/ttyS2` gemountet werden.
Ich hoffe das hilft dir weiter.

**Comment by coelo-donta** [comment]
Hat es funktioniert? Wenn du willst kannst du mir deine Aufstellung senden und ich mache dir das modules.db file.

**Comment by DrMoskovich** [comment]
Hi,
leider hat es nicht geklappt. Aber das wäre sehr nett, wenn sie mir das modules.db file machen könnten.
Ich hätte ein Modul: 
Modul Adresse 1, Minuten, 62 Blätter und COM3.
Vielen Dank schon mal im Voraus.
LG DrMoskovich.

**Comment by coelo-donta** [comment]
Du kannst es damit versuchen. Denk daran, dass verschiedene Funktionen wie Fahrplanabfrage nur mit einer kompletten Anzeige funktionieren. Aber du kannst vom terminal aus `find`, `move`, `step` etc. brauchen oder in der Webansicht die Anzeigen bedienen.
[modules.db.zip](https://github.com/coelo-donta/SBB-fallblatt/files/5604650/modules.db.zip)

**Comment by DrMoskovich** [comment]
Vielen Dank!
